export {default as Home} from "./Home"
export {default as Landing} from "./Landing"
export {default as About} from "./About"
export {default as Services} from "./Services"
export {default as Contact} from "./Contact"
export {default as Booking} from "./Booking"
export {default as SignUp} from "./SignUp"
export {default as Login} from "./SignUp"